/**
 * Woodbury Blender Automat Extension
 *
 * Provides tools to assemble and render videos from JSON project definitions
 * using headless Blender VSE. The JSON format is designed to be generated by an LLM.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { spawn, execSync } from 'node:child_process';

// Common Blender install locations by platform
const BLENDER_PATHS = {
  darwin: [
    '/Applications/Blender.app/Contents/MacOS/Blender',
    '/Applications/Blender.app/Contents/MacOS/blender',
  ],
  linux: ['/usr/bin/blender', '/usr/local/bin/blender', '/snap/bin/blender'],
  win32: [
    'C:\\Program Files\\Blender Foundation\\Blender 4.0\\blender.exe',
    'C:\\Program Files\\Blender Foundation\\Blender 3.6\\blender.exe',
    'C:\\Program Files\\Blender Foundation\\Blender\\blender.exe',
  ],
};

/**
 * Find Blender executable on the system.
 */
function findBlender(hint) {
  if (hint && fs.existsSync(hint)) return hint;

  try {
    const result = execSync('which blender 2>/dev/null || where blender 2>nul', {
      encoding: 'utf8',
      timeout: 5000,
    }).trim();
    if (result) return result.split('\n')[0];
  } catch {
    // Not in PATH
  }

  const candidates = BLENDER_PATHS[process.platform] || [];
  for (const p of candidates) {
    if (fs.existsSync(p)) return p;
  }

  return null;
}

/**
 * Validate a project object (lightweight structural check).
 */
function validateProject(data, baseDir) {
  const errors = [];

  if (!data.version) errors.push('Missing required field: version');
  if (!data.settings) errors.push('Missing required field: settings');
  if (!data.timeline) errors.push('Missing required field: timeline');

  if (data.settings) {
    if (!data.settings.resolution) errors.push('Missing settings.resolution');
    if (!data.settings.fps) errors.push('Missing settings.fps');
    if (!data.settings.output) errors.push('Missing settings.output');
    if (data.settings.output && !data.settings.output.filepath) {
      errors.push('Missing settings.output.filepath');
    }
  }

  if (data.timeline) {
    if (!data.timeline.tracks || !Array.isArray(data.timeline.tracks)) {
      errors.push('Missing or invalid timeline.tracks (must be array)');
    } else {
      data.timeline.tracks.forEach((track, ti) => {
        if (!track.clips || !Array.isArray(track.clips)) {
          errors.push(`Track ${ti} missing clips array`);
          return;
        }
        track.clips.forEach((clip, ci) => {
          if (!clip.type) errors.push(`Track ${ti}, clip ${ci}: missing type`);
          if (clip.start === undefined) errors.push(`Track ${ti}, clip ${ci}: missing start`);
          if (['video', 'image', 'audio'].includes(clip.type) && !clip.asset) {
            errors.push(`Track ${ti}, clip ${ci}: ${clip.type} clip requires 'asset'`);
          }
          if (clip.type === 'text' && (!clip.text || !clip.text.body)) {
            errors.push(`Track ${ti}, clip ${ci}: text clip requires 'text.body'`);
          }
          if (clip.type === 'text' && !clip.duration) {
            errors.push(`Track ${ti}, clip ${ci}: text clip requires 'duration'`);
          }
          if (clip.type === 'color' && !clip.duration) {
            errors.push(`Track ${ti}, clip ${ci}: color clip requires 'duration'`);
          }
          if (clip.asset && data.assets && !data.assets[clip.asset]) {
            errors.push(`Track ${ti}, clip ${ci}: references unknown asset '${clip.asset}'`);
          }
        });
      });
    }
  }

  // Check asset files exist
  if (data.assets && baseDir) {
    for (const [id, asset] of Object.entries(data.assets)) {
      const assetPath = path.isAbsolute(asset.path)
        ? asset.path
        : path.join(baseDir, asset.path);
      if (!fs.existsSync(assetPath)) {
        errors.push(`Asset '${id}': file not found at ${assetPath}`);
      }
    }
  }

  return errors;
}

/**
 * Run Blender headless with the automat_render.py script.
 * Returns a promise that resolves with { code, stdout, stderr }.
 */
function runBlender(blenderPath, renderScript, projectPath, dryRun = false) {
  return new Promise((resolve, reject) => {
    const args = [
      '--background',
      '-noaudio',
      '--python',
      renderScript,
      '--',
      '--project',
      projectPath,
    ];
    if (dryRun) args.push('--dry-run');

    const proc = spawn(blenderPath, args, {
      stdio: ['ignore', 'pipe', 'pipe'],
      env: { ...process.env },
    });

    let stdout = '';
    let stderr = '';

    proc.stdout.on('data', (data) => {
      stdout += data.toString();
    });

    proc.stderr.on('data', (data) => {
      stderr += data.toString();
    });

    proc.on('close', (code) => {
      resolve({ code, stdout, stderr });
    });

    proc.on('error', (err) => {
      reject(new Error(`Failed to start Blender: ${err.message}`));
    });
  });
}

/**
 * @param {import('woodbury').ExtensionContext} ctx
 */
export async function activate(ctx) {
  ctx.log.info('Blender Automat extension activated');

  const blenderHint = ctx.env.BLENDER_PATH || '';
  const automatDir = ctx.env.AUTOMAT_DIR || '';
  const videoOutputDir = ctx.env.VIDEO_OUTPUT_DIR || '';

  // Resolve render script path
  const renderScript = automatDir
    ? path.join(automatDir, 'automat_render.py')
    : '';

  // -------------------------------------------------------------------------
  // Tool: video_render — render a video from a JSON project
  // -------------------------------------------------------------------------
  ctx.registerTool(
    {
      name: 'video_render',
      description: `Render a video from a blender-automat JSON project file or inline JSON object.

Given a JSON project definition, this tool writes it to a temp file, validates it, then runs headless Blender to assemble and render the final video.

**Inputs (provide ONE of):**
- "project_path": path to an existing .json project file on disk
- "project": the full project JSON object (will be written to a temp file)

**Options:**
- "dry_run": if true, builds the Blender timeline but skips the actual render (fast validation)

**Returns:** the output file path on success, or validation/render errors on failure.`,
      parameters: {
        type: 'object',
        properties: {
          project_path: {
            type: 'string',
            description: 'Path to an existing blender-automat project.json file on disk',
          },
          project: {
            type: 'object',
            description: 'Inline blender-automat project JSON object. Will be written to a temp file for rendering.',
          },
          dry_run: {
            type: 'boolean',
            description: 'If true, build the timeline in Blender but skip the render. Useful for validation.',
          },
        },
      },
    },
    async (params) => {
      // Check prerequisites
      if (!automatDir || !fs.existsSync(renderScript)) {
        return JSON.stringify({
          success: false,
          error: `AUTOMAT_DIR not configured or automat_render.py not found. Set AUTOMAT_DIR in the Woodbury dashboard to the blender-automat project directory.`,
        });
      }

      const blender = findBlender(blenderHint);
      if (!blender) {
        return JSON.stringify({
          success: false,
          error: 'Blender not found. Install Blender or set BLENDER_PATH in the Woodbury dashboard.',
        });
      }

      // Determine project path
      let projectPath = params.project_path;
      let tempFile = null;

      if (params.project && !projectPath) {
        // Write inline JSON to a temp file
        const outputDir = videoOutputDir
          ? (path.isAbsolute(videoOutputDir) ? videoOutputDir : path.resolve(ctx.workingDirectory, videoOutputDir))
          : ctx.workingDirectory;
        if (!fs.existsSync(outputDir)) {
          fs.mkdirSync(outputDir, { recursive: true });
        }
        tempFile = path.join(outputDir, `automat_project_${Date.now()}.json`);
        fs.writeFileSync(tempFile, JSON.stringify(params.project, null, 2));
        projectPath = tempFile;
      }

      if (!projectPath) {
        return JSON.stringify({
          success: false,
          error: 'Provide either "project_path" (path to .json file) or "project" (inline JSON object).',
        });
      }

      // Resolve to absolute
      projectPath = path.isAbsolute(projectPath)
        ? projectPath
        : path.resolve(ctx.workingDirectory, projectPath);

      if (!fs.existsSync(projectPath)) {
        return JSON.stringify({
          success: false,
          error: `Project file not found: ${projectPath}`,
        });
      }

      // Load and validate
      let data;
      try {
        data = JSON.parse(fs.readFileSync(projectPath, 'utf8'));
      } catch (e) {
        return JSON.stringify({
          success: false,
          error: `Invalid JSON: ${e.message}`,
        });
      }

      const baseDir = path.dirname(projectPath);
      const errors = validateProject(data, baseDir);
      if (errors.length > 0) {
        return JSON.stringify({
          success: false,
          error: 'Validation failed',
          errors,
        });
      }

      // Resolve output path for the response
      const outputFilepath = data.settings?.output?.filepath || '';
      const resolvedOutput = outputFilepath
        ? (path.isAbsolute(outputFilepath) ? outputFilepath : path.resolve(baseDir, outputFilepath))
        : '';

      // Run Blender
      try {
        const result = await runBlender(blender, renderScript, projectPath, params.dry_run || false);

        // Extract [automat] log lines for a clean summary
        const logLines = result.stdout
          .split('\n')
          .filter((l) => l.includes('[automat]'))
          .join('\n');

        if (result.code !== 0) {
          return JSON.stringify({
            success: false,
            error: `Blender exited with code ${result.code}`,
            log: logLines,
            stderr: result.stderr.slice(-2000),
          });
        }

        return JSON.stringify({
          success: true,
          dry_run: params.dry_run || false,
          output: resolvedOutput || undefined,
          project_file: projectPath,
          blender: blender,
          log: logLines,
        });
      } catch (err) {
        return JSON.stringify({
          success: false,
          error: err.message,
        });
      }
    }
  );

  // -------------------------------------------------------------------------
  // Tool: video_validate — validate a project without rendering
  // -------------------------------------------------------------------------
  ctx.registerTool(
    {
      name: 'video_validate',
      description: `Validate a blender-automat JSON project without rendering. Checks structure, required fields, asset references, and file existence. Fast — does not launch Blender.

**Inputs (provide ONE of):**
- "project_path": path to a .json file
- "project": inline JSON object`,
      parameters: {
        type: 'object',
        properties: {
          project_path: {
            type: 'string',
            description: 'Path to a blender-automat project.json file',
          },
          project: {
            type: 'object',
            description: 'Inline project JSON object to validate',
          },
        },
      },
    },
    async (params) => {
      let data;
      let baseDir = ctx.workingDirectory;

      if (params.project_path) {
        const absPath = path.isAbsolute(params.project_path)
          ? params.project_path
          : path.resolve(ctx.workingDirectory, params.project_path);
        if (!fs.existsSync(absPath)) {
          return JSON.stringify({ valid: false, errors: [`File not found: ${absPath}`] });
        }
        try {
          data = JSON.parse(fs.readFileSync(absPath, 'utf8'));
        } catch (e) {
          return JSON.stringify({ valid: false, errors: [`Invalid JSON: ${e.message}`] });
        }
        baseDir = path.dirname(absPath);
      } else if (params.project) {
        data = params.project;
      } else {
        return JSON.stringify({ valid: false, errors: ['Provide either project_path or project.'] });
      }

      const errors = validateProject(data, baseDir);
      return JSON.stringify({ valid: errors.length === 0, errors });
    }
  );

  // -------------------------------------------------------------------------
  // Command: /automat-status
  // -------------------------------------------------------------------------
  ctx.registerCommand({
    name: 'automat-status',
    description: 'Check Blender Automat configuration status',
    handler: async (args, cmdCtx) => {
      const blender = findBlender(blenderHint);
      if (blender) {
        cmdCtx.print(`Blender: ${blender}`);
      } else {
        cmdCtx.print('Blender: NOT FOUND - install Blender or set BLENDER_PATH');
      }

      if (automatDir && fs.existsSync(renderScript)) {
        cmdCtx.print(`Automat dir: ${automatDir}`);
        cmdCtx.print(`Render script: ${renderScript}`);
      } else {
        cmdCtx.print('Automat dir: NOT CONFIGURED - set AUTOMAT_DIR in dashboard');
      }

      if (videoOutputDir) {
        const resolved = path.isAbsolute(videoOutputDir)
          ? videoOutputDir
          : path.resolve(cmdCtx.workingDirectory, videoOutputDir);
        cmdCtx.print(`Video output: ${resolved}`);
      } else {
        cmdCtx.print('Video output: working directory (no VIDEO_OUTPUT_DIR set)');
      }
    },
  });

  // -------------------------------------------------------------------------
  // System prompt — teaches the LLM how to build project JSON
  // -------------------------------------------------------------------------
  const outputNote = videoOutputDir
    ? `Default video output directory: ${videoOutputDir}`
    : 'Videos are saved to the path specified in settings.output.filepath.';

  ctx.addSystemPrompt(`## Blender Automat Extension (Video Rendering)

You have access to the Blender Automat extension for assembling and rendering videos from JSON project definitions. This runs Blender in headless mode using its Video Sequence Editor.

### Tools

**video_render** — Render a video from a project JSON (inline object or file path).
**video_validate** — Validate a project JSON without rendering.

### Command: /automat-status
Check if Blender and the render script are correctly configured.

### JSON Project Format (version "1.0")

A project has these top-level fields:

\`\`\`json
{
  "version": "1.0",
  "settings": {
    "resolution": { "width": 1920, "height": 1080 },
    "fps": 30,
    "output": {
      "filepath": "./output/video.mp4",
      "format": "MPEG4",
      "codec": "H264",
      "quality": "HIGH",
      "audio_codec": "AAC",
      "audio_bitrate": 192,
      "audio_mixrate": 48000
    }
  },
  "assets": {
    "my_clip": { "type": "video", "path": "./media/clip.mp4" },
    "bg_music": { "type": "audio", "path": "./media/music.mp3" },
    "logo": { "type": "image", "path": "./media/logo.png" }
  },
  "fonts": {
    "heading": { "path": "./fonts/Bold.ttf" }
  },
  "timeline": {
    "duration": "auto",
    "tracks": [ ... ],
    "transitions": [ ... ]
  }
}
\`\`\`

### Clip Types

Each track contains an array of clips. Every clip needs \`type\` and \`start\`.

| Type | Required | Description |
|------|----------|-------------|
| video | asset, start | Video file. Duration defaults to source length. |
| image | asset, start | Still image. Duration defaults to 5s. |
| audio | asset, start | Audio file (MP3, WAV, etc.). |
| text | start, duration, text.body | Text overlay with font/color/shadow/box. |
| color | start, duration, color_value | Solid color strip. |

### Common Clip Properties

All clips support: name, start, duration, source_start, volume (audio/video), opacity (0-1), blend_mode (ALPHA_OVER, ADD, MULTIPLY, CROSS, SUBTRACT, ALPHA_UNDER, OVER_DROP), fade_in, fade_out, transform ({ position: [x,y], scale: [x,y], rotation: degrees }), crop ({ left, right, top, bottom }).

### Text Properties

\`\`\`json
{
  "text": {
    "body": "Hello World",
    "font": "heading",
    "size": 72,
    "color": "#FFFFFF",
    "align_x": "CENTER",
    "align_y": "CENTER",
    "location": [0.5, 0.5],
    "wrap_width": 0.8,
    "use_shadow": true,
    "shadow_color": [0, 0, 0, 0.8],
    "use_box": true,
    "box_color": [0, 0, 0, 0.5],
    "box_margin": 0.01,
    "use_bold": false,
    "use_italic": false
  }
}
\`\`\`

### Transitions

Transitions blend between two named clips:
\`\`\`json
{ "type": "GAMMA_CROSS", "from_clip": "clip_a", "to_clip": "clip_b", "duration": 1 }
\`\`\`
Types: CROSS, GAMMA_CROSS, WIPE.

### Time Values

Seconds (number): 5, 10.5
Timecode (string): "1:30" (1m30s), "1:05:30" (1h5m30s)

### Colors

RGBA array: [1, 1, 1, 1] (values 0.0-1.0)
Hex string: "#FFFFFF" or "#FFFFFF80" (with alpha)

### Output Formats

format: MPEG4, MKV, WEBM, AVI
codec: H264, H265, AV1, WEBM, PRORES
quality: LOSSLESS, PERC_LOSSLESS, HIGH, MEDIUM, LOW, VERYLOW, LOWEST
audio_codec: AAC, AC3, FLAC, MP3, OPUS, VORBIS, PCM, NONE

### Important Notes

- Asset paths are relative to the project JSON file location (or absolute).
- Tracks are layered bottom-to-top (track 0 = bottom layer).
- Clips on higher tracks render on top of lower tracks.
- Use blend_mode: "ALPHA_OVER" for text and overlay clips.
- Named clips (via "name" field) can be referenced in transitions.
- ${outputNote}

### Workflow

1. Gather the user's media files (paths to videos, images, audio).
2. Build the project JSON with assets, timeline tracks, and clips.
3. Call video_validate to check for errors.
4. Call video_render with the project to produce the final video.

### Full Video Pipeline (with other extensions)

For creating videos from scratch and posting to social media:

1. **Generate voiceover:** Use \`tts_speak\` (ElevenLabs) to convert narration text to audio MP3
2. **Generate images:** Use \`nanobanana\` to create images/slides for each section
3. **Assemble video:** Use \`video_render\` with a project JSON that combines the images + audio
4. **Post to social:** Use \`social_attach_video\` then \`social_post_now\` with platform="youtube"

Example flow for "make a YouTube video about X":
- tts_speak(text: narration) → narration.mp3
- nanobanana(prompt: "slide 1 image") → slide1.png
- nanobanana(prompt: "slide 2 image") → slide2.png
- video_render(project: { assets: { narration, slide1, slide2 }, timeline with image+audio tracks })
- social_create_post(text: description, platforms: ["youtube"])
- social_attach_video(postId, videoPath)
- social_post_now(id, platform: "youtube")`);
}

export function deactivate() {
  // Cleanup
}
